In [1]:
import numpy as np

# NumPy Illustrated: The Visual Guide to NumPy

In [2]:
[1,2] + [3]

[1, 2, 3]

In [3]:
# np.array([1,2]) - np.array([3])
# np.array([1,2]) ** np.array([3])
# np.array([1,2]) * np.array([3])
# np.array([1,2]) / np.array([3])

### Numpy Array vs. Python List

### python liste

In [4]:
a = [1,2,3]
[q * 2 for q in a]

[2, 4, 6]

### numpy array

In [5]:
a = np.array([1,2,3])
a * 2

array([2, 4, 6])

### python list 

In [6]:
a = [1,2,3]

b = [4,5,6]
[q+r for q,r in zip(a,b)]

[5, 7, 9]

### numpy array

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a + b

array([5, 7, 9])

## Vectors, the 1D Arrays

### Vector initialization

In [8]:
a = np.array([1.,2.,3.])

In [9]:
a.dtype

dtype('float64')

In [10]:
a.shape

(3,)

### allocation ou reservation de l'espace

In [11]:
b = np.zeros(3,int)  # zeros pour 0 et ones pour 1

In [12]:
b

array([0, 0, 0])

In [13]:
c = np.zeros_like(a)  # Creer un array remplir avec 0 et ayant les caracteristiques de la liste a

In [14]:
c.dtype

dtype('float64')

In [15]:
# l = np.zeros(3)
# l = np.ones(3)
# l = np.empty(3)   
# l = np.full(3,7)

# l = np.zeros_like(a)
# l = np.ones_like(a)
# l = np.empty_like(a)   
# l = np.full_like(a,7)

# l

###  two functions for array initialization
     

In [16]:
# np.arange(start, stop, step) : un peu comme la fonction  range()  
# b = np.arange(6)
# b = np.arange(2,6)
# b = np.arange(1,6,2)

# b

In [17]:
# np.linspace(start,stop,num)  : comme arange()  ici on donne le min et le max ; le pas (step) est automatique
# b = np.linspace(0,0.5,6)
# b

In [18]:
# np.arange(start, stop, step).astype(type_de_donnee)
# b = np.arange(3).astype(float)
# b

In [19]:
# autre maniere de le faire
# b = np.arange(0.4,0.8,0.1)
# b = np.arange(0.5,0.8,0.1)
# b = np.arange(0.5,0.75,0.1)
# b = np.linspace(0.5,0.7,3)
# b = np.linspace(0,1,?)         ???

# b

### valeur random

In [20]:
# v = np.random.randint(0,10,3)  # [0, 10[
# v = np.random.rand(3)  #  [0 , 1[
# v = np.random.randn(2)
# v = np.random.uniform(1,10,3)
# v = np.random.normal(5,2,3)
# v

In [21]:
rng = np.random.default_rng()

In [22]:
# rng.integers(0,10,3)   # [0, 10[
# rng.integers(0,10,3,endpoint=True)   # [0,10]  
# rng.random(3)  # [0, 1[
# rng.standard_normal(3) 
rng.uniform(1,10,3)  # [1, 10[
rng.normal(5,2,3) 

array([5.19418734, 3.75267128, 7.09148342])

## Vector indexing

In [23]:
a = np.arange(1,6) # [1,2,3,4,5]
# a[1]
# a[2:4]
# a[-2:]
# a[::2]
# a[[1,3,4]]
# a[2:4] = 0
# a

### pythno list vs numpy array

In [24]:
# en Python
a = [1,2,3]
b = a  # no copy
c = a[:]  # copy
d = a.copy()

In [25]:
# avec numpy array
a = np.array([1,2,3])
b = a # no copy
c = a[:]  # no copy
d = a.copy()

### affectation multiple

In [26]:
a = [1,2,3]
a[1:2] = [5,6]
a

[1, 5, 6, 3]

In [27]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])
# a > 5
# np.any(a > 5) 
# np.all(a > 5)
# a[a > 5]
# a[a > 5] = 0
# a[(a >=3) & (a<=5)] = 0  # ??? and ne marche
# a

### fonction np.where et np.clip

In [28]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])
# np.where(a > 5)
# np.nonzero(a > 5)
np.where(a > 5 , 1, 0)
# np.clip(a,2,5)  #  

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0])

### Vector operations

In [29]:
a = np.array([1,2])
b = np.array([3,4])
# np.dot(a,b) # Produit scalaire
# np.cross(a,b) # Produit scalaire

In [30]:
# np.sin([np.pi,np.pi/2]) # == [sin(np.pi), sin(np.pi/2)]


* Arrondir

In [31]:
R = [1.1,1.5,1.9,2.5]
# np.floor(R)  # Par defaut
# np.ceil(R)   # par excès 
# np.round(R)  # entier le plus prochaine

* fonction max, min, somme ...

In [32]:
a = np.array([1,2,3])
# a.max()  # le max
# a.min()
# a.sum()   
# a.var()   # variance 
# a.argmax()  # plus grand indice
# a.argmin()    # plus petit indice    ??? peut il etre != 0 
# a.mean()   #moyenne
# a.std()   # Déviation standard  ???
# np.median(a) # mediane


###  fonction de trie  python vs numpy 



In [33]:
# En python 
# a = [4,8,3,6,2,1,0,9,-1]
# a.sort()   # trie ordre croissant
# sorted(a)    # trie ordre croissant
student_tuples = [('john', 'A', 15),('jane', 'B', 12),('dave', 'B', 10),]
student_tuples.sort(key=lambda student: student[2])  # trie avec cle 
student_tuples
# a.sort(reverse=True)  # decroissant
# a

[('dave', 'B', 10), ('jane', 'B', 12), ('john', 'A', 15)]

In [34]:
# avec numpy array
# a = np.array([4,8,3,6,2,1,0,9,-1])
# a.sort()  # trie croissant
# a = np.sort(a) # trie croissant
# a

## Searching for an element in a vector

* python list

In [35]:
a = [4,8,3,6,2,1,0,9,-1] 
a.index(4[,0[,2]])

SyntaxError: invalid syntax (761500997.py, line 2)

In [ ]:
a = np.array([4,8,3,6,2,1,0,9,-1,8,4] )
# np.where(a==6)[0][0]
# next(i[0] for i , v in np.ndenumerate(a) if v==8)  # indice de la premiere occurence ???
# a.sort()
# np.searchsorted(a,6) # indice ???

## Comparing floats 

In [ ]:
# python
0.1 + 0.2 == 0.3 # c'est egale à 0.30000000000000004

In [ ]:
# numpy
np.allclose(0.1 + 0.2,0.3)

In [ ]:
import math
math.isclose(0.1+0.2,0.3)

In [ ]:
1e-9 == 2e-9

In [ ]:
np.allclose(1e-9,2e-9)

In [ ]:
math.isclose(1e-9,2e-9)

In [ ]:
0.1 + 0.2 - 0.3  == 0   # c'est egale à 5.551115123125783e-17

In [ ]:
np.allclose(0.1 + 0.2 - 0.3,0)

In [ ]:
math.isclose(0.1 + 0.2 - 0.3,0)

# 2. Matrices, the 2D Arrays

## Matrix initialization syntax

In [ ]:
# a partir d'une liste python
# a = np.array([
#     [1,2,3],
#     [4,5,6]
# ])
# a.shape   # shape donne (nombre_ligne, nombre_colonne)
# a = np.zeros((3,4))   # remplir de 0 ||  np.zeros((lignes, colonnes))
# a = np.ones((3,4))      #          de 1
# a = np.full((3,4),7)      #          de la valeur qu'on donne
# h = np.empty((3,4))  #                de rien
# h
# a = np.eye(3,5,k=0)    # remplir avec des 1 sur le diagonale a partir de K et des 0 sinon (k peut etre negatif)
# a = np.eye(4,k=0)   # si la matrice est carré 
# a

## Random matrix generation is also similar to that of vectors

In [ ]:
# a = np.random.randint(0,10,(3,4))   # (borne_inf, borne_sup, (lignes, colonnes))
# a = np.random.rand(3,4)  # valeur entre 0 et 0
# a

In [ ]:
# a = np.array([
#     [1,2,3,4],
#     [5,6,7,8],
#     [9,10,11,12]
# ])
# a[1,2]  # a[ligne, colonne]
# a[2,:]    # a[ligne,:]
# a[:,2]   # a[:,colonne]
# a[::3,:]  # :: ligne_a_exclure ou colonne
# a.sum()
# a.sum(axis=0)  # somme de colonne
# a.sum(axis=1)  # somme de ligne


## operation 

In [ ]:
# a = np.array([
#     [1,2],
#     [3,4]
# ])
# b = np.array([
#     [3,1],
#     [2,4]
# ])
# a + b  
# a - b
# a * b
# a / b
# a ** b
# b @ a 

In [ ]:
M = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
# M / 9  # equvalent à  M / [[9,9,9],[9,9,9],[9,9,9]]
# M * [-1,0,1] # equivalent à M * [[-1,0,1],[-1,0,1],[-1,0,1]]
M / [[3],[6],[9]] # equivalent à M * [[3,3,3],[6,6,6],[9,9,9]]


In [ ]:
# a = np.array([[1,2,3],[4,5,6]])
# a.T  # les lignes deviennent des colonnes et les colonnes des lignes
b = np.array([[1],[2],[3]])
b * b.T

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a.reshape(1,-1)

In [ ]:
a.reshape(-1,1)

In [ ]:
a.reshape(3,3)

## Matrix manipulations

In [ ]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
c = np.array([
    [1,2],
    [3,4],
    [5,6]
])
b = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
# np.hstack((a,c)) # ajout horizontal
# np.vstack((a,b))   # ajout vertical
y = np.hstack((a,c))
# np.hsplit(y,[3])  # split

In [ ]:
 a = np.array([
     [1,2],
     [3,4]
 ])
# np.tile(a,(2,3)) # repliquer (ligne , colonne)
# a.repeat(2,axis=0) # repeter selon l'axe (axis = 0 en ligne et axis = 1 en colonne)

In [ ]:
a = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12]])
# np.delete(a,[1],axis=1)  # supprimer ligne ou colonne selon (axis)
np.delete(a,slice(1,-1),axis=0)

* la focntion append

In [ ]:
a = np.array([
    [1,  2, 3, 4, 5],
    [6,  7, 8, 9, 10],
    [11, 12,13,14,15]])
# np.append(a, np.zeros(5), axis=0)
# np.column_stack(a,np.zeros(3))
# a

* fonction pad

In [ ]:
a = np.array([
    [1,  2, 3, 4, 5],
    [6,  7, 8, 9, 10],
    [11, 12,13,14,15]])
# np.pad(a,((0,0),(0,2)))
# np.pad(a,((0,1),(0,0)))
# np.pad(a,((1,1),(1,1)))  # np.pad(a,1)

## Matrix statistics

In [ ]:
a = np.array([
    [4,8,5],
    [9,3,1]
])
# a.min() # le min parmit toutes les cases
# a.max() # le max parmit toutes les cases
# a.argmin()
# on peut utilise l'argment axis=0 pour la ligne et axis=1 pour la colnne

* any et all

In [ ]:
# np.any(a>5)
# np.all(a>5)
#On peut aussi utiliser axis comme deuxieme argument

## Matrix sorting

In [ ]:
# a = np.array([
#     [4,8,5],
#     [9,3,1]
# ])
# a.sort() # axis pour spécifier la ligne ou la colnne
# a

In [ ]:
# a = np.array([
#     [3,4],
#     [2,7],
#     [1,5],
#     [2,6]
# ])
# b = np.rot90(a)
# c = np.lexsort(b)
# a[c]

# 3D and Above

* initialisation

In [ ]:
a = np.arange(1,9).reshape(2,2,2)
a

In [ ]:
a = np.array([
    [
        [0,0,0,0],
        [0,0,0,0]
    ],
    [
        [1,1,1,1],
        [1,1,1,1]
    ],
    [
        [2,2,2,2],
        [2,2,2,2]
    ]
])
# a.shape   # les dimensions lignes colonnes et profondeurs
# a.ndim  la dimension 
# a.size
np.dstack(a)

In [ ]:
a = np.array([
    [[0,1,2],[0,1,2],[0,1,2],[0,1,2]],
    [[0,1,2],[0,1,2],[0,1,2],[0,1,2]]
    
])
# a.shape
# np.dstack(a)

###   Creation generique

In [ ]:
# a = np.zeros((3,4,5))
# a = np.zeros((4,5,3))
# a = np.ones((3,4,5))
# a = np.ones((4,5,3))

# a = np.random.rand(3,4,5)
# a = np.random.rand(4,5,3)


# a

* concatenate des array 3D

In [ ]:
a = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
])
b = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
])

c = np.array([
    [
        [1,2],
        [5,6],
        [9,10]
    ],
    [
        [1,2],
        [5,6],
        [9,10]
    ]
])

d = np.array([
    [
        [0,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [0,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
])

# np.concatenate((a,b),axis=1)
# np.concatenate((a,c),axis=2)
# np.concatenate((a,d),axis=0)
np.concatenate((a,d))

In [ ]:
a = np.array([
    [
        [0,0,0,0],
        [0,0,0,0]
    ],
    [
        [1,1,1,1],
        [1,1,1,1]
    ],
    [
        [2,2,2,2],
        [2,2,2,2]
    ]
])
# np.moveaxis(a,0,2)
# np.dstack(a)

In [ ]:
a = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [-1,-2,-3,-4],
        [-5,-6,-7,-8],
        [-9,-10,-11,-12]
    ]
])
# np.swapaxes(a,0,1)
# np.swapaxes(a,1,2)
# np.swapaxes(a,0,2)
# a.T

In [ ]:
a = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]
])

b = np.array([
    [
        [-1,-2,-3,-4],
        [-5,-6,-7,-8],
        [-9,-10,-11,-12]
    ]
])

np.einsum('ij,jk->ik',a,b)